/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicTermsIndexRouteImport } from './routes/(public)/terms/index'
import { Route as publicPrivacyIndexRouteImport } from './routes/(public)/privacy/index'
import { Route as publicsiteIndexRouteImport } from './routes/(public)/(site)/index'
import { Route as protectedPlaylistIndexRouteImport } from './routes/(protected)/playlist/index'
import { Route as protectedHomeIndexRouteImport } from './routes/(protected)/home/index'
import { Route as protectedAudioIndexRouteImport } from './routes/(protected)/audio/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as protectedPlaylistIdIndexRouteImport } from './routes/(protected)/playlist/$id/index'
import { Route as protectedAudioIdIndexRouteImport } from './routes/(protected)/audio/$id/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicTermsIndexRoute = publicTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyIndexRoute = publicPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicsiteIndexRoute = publicsiteIndexRouteImport.update({
  id: '/(site)/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedPlaylistIndexRoute = protectedPlaylistIndexRouteImport.update({
  id: '/(protected)/playlist/',
  path: '/playlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedHomeIndexRoute = protectedHomeIndexRouteImport.update({
  id: '/(protected)/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAudioIndexRoute = protectedAudioIndexRouteImport.update({
  id: '/(protected)/audio/',
  path: '/audio/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedPlaylistIdIndexRoute =
  protectedPlaylistIdIndexRouteImport.update({
    id: '/(protected)/playlist/$id/',
    path: '/playlist/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedAudioIdIndexRoute = protectedAudioIdIndexRouteImport.update({
  id: '/(protected)/audio/$id/',
  path: '/audio/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/audio': typeof protectedAudioIndexRoute
  '/home': typeof protectedHomeIndexRoute
  '/playlist': typeof protectedPlaylistIndexRoute
  '/': typeof publicsiteIndexRoute
  '/privacy': typeof publicPrivacyIndexRoute
  '/terms': typeof publicTermsIndexRoute
  '/audio/$id': typeof protectedAudioIdIndexRoute
  '/playlist/$id': typeof protectedPlaylistIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/audio': typeof protectedAudioIndexRoute
  '/home': typeof protectedHomeIndexRoute
  '/playlist': typeof protectedPlaylistIndexRoute
  '/': typeof publicsiteIndexRoute
  '/privacy': typeof publicPrivacyIndexRoute
  '/terms': typeof publicTermsIndexRoute
  '/audio/$id': typeof protectedAudioIdIndexRoute
  '/playlist/$id': typeof protectedPlaylistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(protected)/audio/': typeof protectedAudioIndexRoute
  '/(protected)/home/': typeof protectedHomeIndexRoute
  '/(protected)/playlist/': typeof protectedPlaylistIndexRoute
  '/(public)/(site)/': typeof publicsiteIndexRoute
  '/(public)/privacy/': typeof publicPrivacyIndexRoute
  '/(public)/terms/': typeof publicTermsIndexRoute
  '/(protected)/audio/$id/': typeof protectedAudioIdIndexRoute
  '/(protected)/playlist/$id/': typeof protectedPlaylistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/audio'
    | '/home'
    | '/playlist'
    | '/'
    | '/privacy'
    | '/terms'
    | '/audio/$id'
    | '/playlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/audio'
    | '/home'
    | '/playlist'
    | '/'
    | '/privacy'
    | '/terms'
    | '/audio/$id'
    | '/playlist/$id'
  id:
    | '__root__'
    | '/(public)'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(protected)/audio/'
    | '/(protected)/home/'
    | '/(protected)/playlist/'
    | '/(public)/(site)/'
    | '/(public)/privacy/'
    | '/(public)/terms/'
    | '/(protected)/audio/$id/'
    | '/(protected)/playlist/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  protectedAudioIndexRoute: typeof protectedAudioIndexRoute
  protectedHomeIndexRoute: typeof protectedHomeIndexRoute
  protectedPlaylistIndexRoute: typeof protectedPlaylistIndexRoute
  protectedAudioIdIndexRoute: typeof protectedAudioIdIndexRoute
  protectedPlaylistIdIndexRoute: typeof protectedPlaylistIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/terms/': {
      id: '/(public)/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy/': {
      id: '/(public)/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(site)/': {
      id: '/(public)/(site)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicsiteIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/playlist/': {
      id: '/(protected)/playlist/'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof protectedPlaylistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/home/': {
      id: '/(protected)/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof protectedHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/audio/': {
      id: '/(protected)/audio/'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof protectedAudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/playlist/$id/': {
      id: '/(protected)/playlist/$id/'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof protectedPlaylistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/audio/$id/': {
      id: '/(protected)/audio/$id/'
      path: '/audio/$id'
      fullPath: '/audio/$id'
      preLoaderRoute: typeof protectedAudioIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface publicRouteRouteChildren {
  publicsiteIndexRoute: typeof publicsiteIndexRoute
  publicPrivacyIndexRoute: typeof publicPrivacyIndexRoute
  publicTermsIndexRoute: typeof publicTermsIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicsiteIndexRoute: publicsiteIndexRoute,
  publicPrivacyIndexRoute: publicPrivacyIndexRoute,
  publicTermsIndexRoute: publicTermsIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  protectedAudioIndexRoute: protectedAudioIndexRoute,
  protectedHomeIndexRoute: protectedHomeIndexRoute,
  protectedPlaylistIndexRoute: protectedPlaylistIndexRoute,
  protectedAudioIdIndexRoute: protectedAudioIdIndexRoute,
  protectedPlaylistIdIndexRoute: protectedPlaylistIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
