/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as homeIdIndexRouteImport } from './routes/(home)/$id/index'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIdIndexRoute = homeIdIndexRouteImport.update({
  id: '/(home)/$id/',
  path: '/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/$id': typeof homeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/$id': typeof homeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/(home)/$id/': typeof homeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$id'
  id: '__root__' | '/(home)/' | '/(home)/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  homeIdIndexRoute: typeof homeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/$id/': {
      id: '/(home)/$id/'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof homeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  homeIdIndexRoute: homeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
