/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as homePlaylistIndexRouteImport } from './routes/(home)/playlist/index'
import { Route as homeAudioIndexRouteImport } from './routes/(home)/audio/index'
import { Route as homePlaylistIdIndexRouteImport } from './routes/(home)/playlist/$id/index'
import { Route as homeAudioIdIndexRouteImport } from './routes/(home)/audio/$id/index'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homePlaylistIndexRoute = homePlaylistIndexRouteImport.update({
  id: '/(home)/playlist/',
  path: '/playlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeAudioIndexRoute = homeAudioIndexRouteImport.update({
  id: '/(home)/audio/',
  path: '/audio/',
  getParentRoute: () => rootRouteImport,
} as any)
const homePlaylistIdIndexRoute = homePlaylistIdIndexRouteImport.update({
  id: '/(home)/playlist/$id/',
  path: '/playlist/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeAudioIdIndexRoute = homeAudioIdIndexRouteImport.update({
  id: '/(home)/audio/$id/',
  path: '/audio/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/audio': typeof homeAudioIndexRoute
  '/playlist': typeof homePlaylistIndexRoute
  '/audio/$id': typeof homeAudioIdIndexRoute
  '/playlist/$id': typeof homePlaylistIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/audio': typeof homeAudioIndexRoute
  '/playlist': typeof homePlaylistIndexRoute
  '/audio/$id': typeof homeAudioIdIndexRoute
  '/playlist/$id': typeof homePlaylistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/(home)/audio/': typeof homeAudioIndexRoute
  '/(home)/playlist/': typeof homePlaylistIndexRoute
  '/(home)/audio/$id/': typeof homeAudioIdIndexRoute
  '/(home)/playlist/$id/': typeof homePlaylistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audio' | '/playlist' | '/audio/$id' | '/playlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audio' | '/playlist' | '/audio/$id' | '/playlist/$id'
  id:
    | '__root__'
    | '/(home)/'
    | '/(home)/audio/'
    | '/(home)/playlist/'
    | '/(home)/audio/$id/'
    | '/(home)/playlist/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  homeAudioIndexRoute: typeof homeAudioIndexRoute
  homePlaylistIndexRoute: typeof homePlaylistIndexRoute
  homeAudioIdIndexRoute: typeof homeAudioIdIndexRoute
  homePlaylistIdIndexRoute: typeof homePlaylistIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/playlist/': {
      id: '/(home)/playlist/'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof homePlaylistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/audio/': {
      id: '/(home)/audio/'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof homeAudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/playlist/$id/': {
      id: '/(home)/playlist/$id/'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof homePlaylistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/audio/$id/': {
      id: '/(home)/audio/$id/'
      path: '/audio/$id'
      fullPath: '/audio/$id'
      preLoaderRoute: typeof homeAudioIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  homeAudioIndexRoute: homeAudioIndexRoute,
  homePlaylistIndexRoute: homePlaylistIndexRoute,
  homeAudioIdIndexRoute: homeAudioIdIndexRoute,
  homePlaylistIdIndexRoute: homePlaylistIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
